### ISSUE TITLE
Another crash on running birdgrid_timeseries

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#13]
This time I get this error, which seems to reference a variable not defined within the function or passed in as an argument:

```
wifi_guest-10-38-112-188:birdgrid kazjon$ python birdgrid_timeseries.py 
/Library/Python/2.7/site-packages/pandas/io/parsers.py:1070: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)
/Library/Python/2.7/site-packages/pandas/core/common.py:361: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask = arr == x
/Users/kazjon/Dropbox/Documents/PyCharmProjects/birdgrid/birdgridhelpers.py:50: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead
  GridSquare['LATITUDE']=i
/Users/kazjon/Dropbox/Documents/PyCharmProjects/birdgrid/birdgridhelpers.py:51: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead
  GridSquare['LONGITUDE']=j
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "birdgrid_timeseries.py", line 33, in <module>
    plot_birds_over_time(location,SPECIES)
  File "/Users/kazjon/Dropbox/Documents/PyCharmProjects/birdgrid/birdgridhelpers.py", line 120, in plot_birds_over_time
    Timestamp = [dt.datetime.strptime(d,'%m/%Y').date() for d in Timestamp]
NameError: global name 'dt' is not defined
```

**Comment by SwarnaVallurupalli** [comment]
I have corrected it Kaz. I haven't imported 'datetime'  package before referencing it as variable. I had fixed it. It should work fine now.
