### ISSUE TITLE
Crash bug in model_location_novelty_over_time

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#20]
It looks like there's an attempt to retrieve a non-existent entry from something when I run birdgrid_timeseries.  Have you seen something like this?  If not, I can provide more details as to what's different in my setup.

```
Traceback (most recent call last):
  File "birdgrid_timeseries.py", line 37, in <module>
    predictors.append(model_location_novelty_over_time(location,SPECIES,SEASONS,START_YEAR,END_YEAR))
  File "/Users/kazjon/Dropbox/Documents/PyCharmProjects/birdgrid/birdgridhelpers.py", line 167, in model_location_novelty_over_time
    Train_Data['PERIOD'] = Train_Data.YEAR.astype(str).str.cat(Train_Data.MONTH.astype(str))
  File "/Library/Python/2.7/site-packages/pandas/core/strings.py", line 862, in cat
    result = str_cat(self.series, others=others, sep=sep, na_rep=na_rep)
  File "/Library/Python/2.7/site-packages/pandas/core/strings.py", line 42, in str_cat
    arrays = _get_array_list(arr, others)
  File "/Library/Python/2.7/site-packages/pandas/core/strings.py", line 14, in _get_array_list
    if isinstance(others[0], (list, np.ndarray)):
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 491, in __getitem__
    result = self.index.get_value(self, key)
  File "/Library/Python/2.7/site-packages/pandas/core/index.py", line 1032, in get_value
    return self._engine.get_value(s, k)
  File "index.pyx", line 97, in pandas.index.IndexEngine.get_value (pandas/index.c:2661)
  File "index.pyx", line 105, in pandas.index.IndexEngine.get_value (pandas/index.c:2476)
  File "index.pyx", line 149, in pandas.index.IndexEngine.get_loc (pandas/index.c:3215)
  File "hashtable.pyx", line 382, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6450)
  File "hashtable.pyx", line 388, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6394)
KeyError: 0
```

**Comment by SwarnaVallurupalli** [comment]
Kaz, the code worked  fine for me when I tried. I haven't got any error like that. Could you please try the most recent code from github and check once again.

**Comment by Kazjon** [comment]
I'm afraid it does the same thing with the most recent code.  I'll take another look at it tomorrow and dig into what's actually happening.
